## Creating DataFrames

### From Python Lists

In [2]:
import pandas as pd

In [2]:
data = [
    ["Alice" , 24],
    ["bob",39],
    ["charlie",34]
]

In [4]:
df = pd.DataFrame(data,columns=["name","age"])

In [5]:
df

      name  age
0    Alice   24
1      bob   39
2  charlie   34

### From Dictionary of Lists

In [6]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}

df = pd.DataFrame(data)

In [7]:
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

### Each key becomes a column, and each list is the column data.

### From NumPy Arrays

In [9]:
import numpy as np

In [10]:
arr = np.array([[1,2],[4,5]])
arr

array([[1, 2],
       [4, 5]])

In [17]:
df = pd.DataFrame(arr,columns = ["a","b"])

In [18]:
df

   a  b
0  1  2
1  4  5

### From CSV Files

In [10]:
df = pd.read_csv("../datasets/data.csv") # Comma Seperated Values

In [9]:
df.head()

   Roll No             Name                      School       City  Marks
0        1     Aarav Sharma  Himalayan Secondary School  Kathmandu     82
1        2       Sita Karki       Greenland High School   Lalitpur     76
2        3      Rohan Thapa             Everest Academy  Bhaktapur     88
3        4  Anisha Shrestha             Capital College  Kathmandu     91
4        5     Bibek Gurung           Mount View School    Pokhara     73

In [12]:
pd.read_csv("../datasets/data.csv" , usecols=["Name","City"])

                Name        City
0       Aarav Sharma   Kathmandu
1         Sita Karki    Lalitpur
2        Rohan Thapa   Bhaktapur
3    Anisha Shrestha   Kathmandu
4       Bibek Gurung     Pokhara
5       Pratik Joshi   Kathmandu
6          Sneha Rai      Dharan
7    Manish Bhandari    Lalitpur
8       Alisha Magar      Butwal
9     Saroj Adhikari   Kathmandu
10    Krisha Neupane   Kathmandu
11        Rajiv Lama     Hetauda
12      Divya Poudel  Biratnagar
13         Sushan KC   Kathmandu
14       Elina Joshi   Bhaktapur
15  Nirajan Shrestha    Lalitpur
16      Samir Tamang   Kathmandu
17      Asmita Thapa   Kathmandu
18       Prabesh Rai      Dharan
19     Bishal Gurung     Pokhara

In [13]:
df.head()

   Roll No             Name                      School       City  Marks
0        1     Aarav Sharma  Himalayan Secondary School  Kathmandu     82
1        2       Sita Karki       Greenland High School   Lalitpur     76
2        3      Rohan Thapa             Everest Academy  Bhaktapur     88
3        4  Anisha Shrestha             Capital College  Kathmandu     91
4        5     Bibek Gurung           Mount View School    Pokhara     73

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Roll No  20 non-null     int64
 1   Name     20 non-null     object
 2   School   20 non-null     object
 3   City     20 non-null     object
 4   Marks    20 non-null     int64
dtypes: int64(2), object(3)
memory usage: 932.0+ bytes

In [16]:
df.describe()

        Roll No    Marks
count  20.00000  20.0000
mean   10.50000  80.4000
std     5.91608   8.5557
min     1.00000  67.0000
25%     5.75000  73.7500
50%    10.50000  80.5000
75%    15.25000  87.2500
max    20.00000  95.0000

### From Excel Files

df = pd.read_excel("data.xlsx")

### From JSON

df = pd.read_json("data.json")

### From SQL Databases

In [19]:
# import sqlite3

# conn = sqlite3.connect("mydb.sqlite")
# df = pd.read_sql("SELECT * FROM users", conn)

### From the Web

In [20]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"

In [21]:
df = pd.read_csv(url)

In [22]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

## EDA (Exploratory Data Analysis)

Exploratory Data Analysis (EDA) is an essential first step in any data science project.

It involves taking a deep look at the dataset to understand its structure, spot patterns, identify anomalies, and uncover relationships between variables. This process includes generating summary statistics, checking for missing or duplicate data, and creating visualizations like histograms, box plots, and scatter plots. 

- The goal of EDA is to get a clear picture of what the data is telling you before applying any analysis or machine learning models.

In [23]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4