## Creating DataFrames

### From Python Lists

In [1]:
import pandas as pd

In [2]:
data = [
    ["Alice" , 24],
    ["bob",39],
    ["charlie",34]
]

In [4]:
df = pd.DataFrame(data,columns=["name","age"])

In [5]:
df

      name  age
0    Alice   24
1      bob   39
2  charlie   34

### From Dictionary of Lists

In [6]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}

df = pd.DataFrame(data)

In [7]:
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

### Each key becomes a column, and each list is the column data.

### From NumPy Arrays

In [9]:
import numpy as np

In [10]:
arr = np.array([[1,2],[4,5]])
arr

array([[1, 2],
       [4, 5]])

In [17]:
df = pd.DataFrame(arr,columns = ["a","b"])

In [18]:
df

   a  b
0  1  2
1  4  5

### From CSV Files

In [19]:
df = pd.read_csv("data.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'